---
display_name:
  required: true
  default_value:
  value_type: string
description:
  required: false
  default_value:
  value_type: string
project_email:
  required: true
  default_value:
  value_type: string
github_teams:
  required: false
  default_value:
  value_type: array
google_groups:
  required: false
  default_value:
  value_type: array
